apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-db  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-management-db
  template:
    metadata:
      labels:
        app: customer-management-db
    spec:
      containers:
        - name: customer-management-db
          image: postgres:10.1 # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres-pv-claim